export const TP_PARAMETROS = {
  TP_REGISTRO: 1,
  TP_RETORNA_A: 3,
  TP_PREGUNTA: 6 , 
  TP_CONTENIDO: 4,
  TP_CONDICION: 7,
  TP_STRESS: 25,
  TP_CABEZA: 17,
  TP_GARGANTA: 18,
  TP_BRAZOS: 19,
  TP_ESTOMAGO: 20,
  TP_ZONA_GENITAL: 21,
  TP_PIERNAS: 22
};
